name: Use Shared CI/CD Template
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    uses: akfa-uz/ci-cd-templates/.github/workflows/mvp-35.yml@main  #with-dockerfile.yml  #docker-with-args.yml
    with:
      image_name: ${{ github.ref_name == 'dev' && 'dev_ai_scratch' || github.ref_name == 'main' && 'ai_scratch' }}
      service_name: ${{ github.ref_name == 'dev' && 'dev_ai_scratch' || github.ref_name == 'main' && 'ai_scratch' }}
#      use_arg: postgresql://ak_admission_user:gAjls4d4HcKuxS7JqhPnC2ij5bCFEJi6wxbNNHfd0nYyt1Ux4tjfOUwILc@10.7.9.28:57926/be_student_dev?schema=public
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  notify-dev:
    if: github.ref_name == 'dev' && always() # Run no matter what
    needs: deploy
    uses: akfa-uz/ci-cd-templates/.github/workflows/discord.yml@main
    with:
      status: ${{ needs.deploy.result }} # Will be "success", "failure", or "cancelled"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEV_CI_CD }}
  notify-dev-02:
    if: github.ref_name == 'dev-02' && always() # Run no matter what
    needs: deploy
    uses: akfa-uz/ci-cd-templates/.github/workflows/discord.yml@main
    with:
      status: ${{ needs.deploy.result }} # Will be "success", "failure", or "cancelled"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEV_CI_CD }}

  notify-main:
    if: github.ref_name == 'main' && always() # Run no matter what
    needs: deploy
    uses: akfa-uz/ci-cd-templates/.github/workflows/discord.yml@main
    with:
      status: ${{ needs.deploy.result }} # Will be "success", "failure", or "cancelled"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CI_CD }}
